
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Mar 02 23:49:49 EST 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class A3Symbol {
  /* terminals */
  public static final int error = 1;
  public static final int PLUS = 2;
  public static final int NUMBER = 6;
  public static final int IDENTIFIER = 7;
  public static final int MINUS = 3;
  public static final int DIVIDE = 5;
  public static final int TIMES = 4;
  public static final int EOF = 0;
}

