
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Mar 03 14:04:59 EST 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class A3Symbol {
  /* terminals */
  public static final int TIMES = 4;
  public static final int READ = 10;
  public static final int SEMICOLON = 18;
  public static final int ELSE = 12;
  public static final int PLUS = 2;
  public static final int RPAREN = 8;
  public static final int IDENTIFIER = 22;
  public static final int END = 15;
  public static final int RETURN = 13;
  public static final int TYPEDEFS = 20;
  public static final int IF = 11;
  public static final int QUOTEDSTRING = 6;
  public static final int LPAREN = 7;
  public static final int WRITE = 9;
  public static final int BEGIN = 14;
  public static final int CONDITIONAL = 17;
  public static final int COMMA = 19;
  public static final int NUMBER = 23;
  public static final int EOF = 0;
  public static final int DIVIDE = 5;
  public static final int MAIN = 16;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int ASSIGN = 21;
}

